/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Schoolware.UI.Template;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author yukun
 */
public class TimerPanel extends javax.swing.JPanel implements ActionListener {

    Timer timer;
    long initTime;

    /**
     * Creates new form TimerPanel
     */
    public TimerPanel(long start, int interval) {
        initComponents();
        timer = new Timer(0, this);
        timer.setDelay(interval);
        initTime = System.currentTimeMillis() - start;
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setText("time past:");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        this.jLabel1.setText("    time past: " + getTimePast() / 1000 + " second");
    }

    public long getTimePast() {
        return System.currentTimeMillis() - initTime;
    }

    public static void main(String args[]) {
        JFrame frame = new JFrame();
        TimerPanel test = new TimerPanel(0, 100);
        frame.add(test);
        frame.setLocationRelativeTo(null);
        frame.setSize(500, 350);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
}
